### PR TITLE
Add support for centos 7 containers

### PR DESCRIPTION
**Pull request by yagnik**
Added docker files to support centos 7
I decided to use the officual centos-7  images for minimal as opposed to from a user.

Tested creation of all three docker containers. Do I need to do any further testing to ensure that I didn't miss anything else ?

### CODE REVIEW

**Comment by yagnik** [comment]
cc @cachedout @s0undt3ch

**Comment by cachedout** [comment]
Nice! Thanks, @yagnik

**Comment by yagnik** [comment]
@s0undt3ch @cachedout can we push this to dockerhub ? Currently it points to @s0undt3ch 's fork

**Comment by cachedout** [comment]
That's a question for @s0undt3ch

**Pull request merged**
